import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
 
const lexend = Lexend({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable}`} >{children}</body>
    </html>
  );
}
